# Generated by rust2rpm-9-1.fc30
%bcond_with check
%global debug_package %{nil}

%global crate mime_guess

Name:           rust-%{crate}1
Version:        1.8.7
Release:        3%{?dist}
Summary:        Simple crate for detection of a file's MIME type by its extension

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/mime_guess
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(mime/default) >= 0.1.0 with crate(mime/default) < 0.3.0)
BuildRequires:  (crate(phf/default) >= 0.7.0 with crate(phf/default) < 0.8.0)
BuildRequires:  (crate(phf/unicase) >= 0.7.0 with crate(phf/unicase) < 0.8.0)
BuildRequires:  (crate(phf_codegen/default) >= 0.7.0 with crate(phf_codegen/default) < 0.8.0)
BuildRequires:  (crate(unicase/default) >= 1.1.0 with crate(unicase/default) < 2.0.0)

%global _description \
A simple crate for detection of a file's MIME type by its extension.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.8.7-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.8.7-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Mon Jun 03 2019 Josh Stone <jistone@redhat.com> - 1.8.7-1
- Update to 1.8.7

* Mon Mar 11 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.8.6-1
- Initial package
